version: '3.8'

services:
  apache:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
